version: "2.1"

services:
  game_ui:
    container_name: game_ui_otus
    depends_on:
      game_controller_api:
        condition: service_healthy
    build: GameUI
    ports:
    - 8080:4200
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 10s
      timeout: 5s
      retries: 5

  game_controller_api:
    container_name: game_controller_api_otus
    depends_on:
      rabbitmq:
        condition: service_healthy
      game_controller_db:
        condition: service_healthy
    build: GameController
    ports:
    - 7070:7196
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://+:7196
    - RABBITMQ__HOSTNAME=rabbitmq
    - RABBITMQ__PORT=5672
    - RABBITMQ__USERNAME=game-controller
    - RABBITMQ__PASSWORD=Gc1234
    - RABBITMQ__VIRTUALHOST=/
    - RABBITMQ__NEWDAYEXCHANGENAME=x_new_day
    - RABBITMQ__NEWDAYQUEUENAMEGENERATOR=q_new_day_generator
    - RABBITMQ__NEWDAYQUEUENAMESHIP=q_new_day_ship
    - DATABASE_HOSTNAME=game_controller_db
    - DATABASE_PORT=5432
    - DATABASE_NAME=game_controller
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=pg_pass
    - SPACESHIPAPI__HOSTNAME=spaceship_webapi
    - SPACESHIPAPI__PORT=5216
    - GENERATORAPI__HOSTNAME=generator_webapi
    - GENERATORAPI__PORT=7161
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7196/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  game_controller_db:
    container_name: game_controller_db_otus
    image: postgres
    ports:
    - 5050:5432
    environment:
    - POSTGRES_DB=game_controller
    - POSTGRES_PASSWORD=pg_pass
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - game_controller_otus_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 50s

  spaceship_webapi:
    image: spaceship-webapi
    container_name: spaceship_webapi_otus
    depends_on:
      game_controller_db:
        condition: service_healthy
    build: SpaceShip
    ports:
    - 5051:5216
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://+:5216
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_USER=space-ship
    - RABBITMQ_PASSWORD=Ss1234
    - RABBITMQ_TROUBLES_QUEUE=q_troubles
    - RABBITMQ_STEP_QUEUE=q_new_day_ship
    - POSTGRES_HOST=game_controller_db
    - POSTGRES_PORT=5432
    - POSTGRES_DATABASE=spaceship_db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=pg_pass
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5216/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  generator_webapi:
    image: generator-webapi
    container_name: generator_webapi_otus
    depends_on:
      game_controller_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    build: EventGenerator
    ports:
    - 6061:7161
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://+:7161
    - DATABASE_HOSTNAME=game_controller_db
    - DATABASE_PORT=5432
    - DATABASE_NAME=event_generator_db
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=pg_pass
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_USER=problem-generator
    - RABBITMQ_PASSWORD=Pg1234
    - RABBITMQ_NEW_DAY_EXCHANGE=x_new_day
    - RABBITMQ_NEW_DAY_QUEUE=q_new_day_generator
    - RABBITMQ_EVENTS_EXCHANGE=x_events
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7161/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    container_name: rabbitmq_otus
    build: RabbitMQ
    hostname: rabbitmq-otus
    ports:
    - 15672:15672
    - 5672:5672
    volumes:
    - rabbitmq_otus_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_otus_data:
  game_controller_otus_pg_data:
