services:
  game_controller_api:
    container_name: game_controller_api_otus
    build: GameController
    ports:
    - 7070:7196
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=https://+:7196
    - RABBITMQ_HOSTNAME=rabbitmq
    - RABBITMQ_PORT=5672
    - RABBITMQ_USERNAME=game-controller
    - RABBITMQ_PASSWORD=Gc1234
    - RABBITMQ_VIRTUALHOST=/
    - EXCHANGENAME_NEWDAY=x_new_day

    - QUEUENAME_NEWDAY_GENERATOR=q_new_day_generator
    - QUEUENAME_NEWDAY_SHIP=q_new_day_ship

  rabbitmq:
    container_name: rabbitmq_otus
    build: RabbitMQ
    hostname: rabbitmq-otus
    ports:
    - 15672:15672
    - 5672:5672
    volumes:
    - rabbitmq_otus_data:/var/lib/rabbitmq

volumes:
  rabbitmq_otus_data:
