version: "2.1"

services:
  game_controller_api:
    container_name: game_controller_api_otus
    depends_on:
      rabbitmq:
        condition: service_healthy
    build: GameController
    ports:
    - 7070:7196
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=https://+:7196
    - RABBITMQ__HOSTNAME=rabbitmq
    - RABBITMQ__PORT=5672
    - RABBITMQ__USERNAME=game-controller
    - RABBITMQ__PASSWORD=Gc1234
    - RABBITMQ__VIRTUALHOST=/
    - RABBITMQ__NEWDAYEXCHANGENAME=x_new_day
    - RABBITMQ__NEWDAYQUEUENAMEGENERATOR=q_new_day_generator
    - RABBITMQ__NEWDAYQUEUENAMESHIP=q_new_day_ship
    - DATABASE_HOSTNAME=game_controller_db
    - DATABASE_PORT=5432
    - DATABASE_NAME=game_controller
    - DATABASE_USER=postgres
    - DATABASE_PASSWORD=pg_pass
    - SPACESHIPAPI__HOSTNAME=spaceship_webapi
    - SPACESHIPAPI__PORT=5216

  game_controller_db:
    container_name: game_controller_db_otus
    image: postgres
    ports:
    - 5050:5432
    environment:
    - POSTGRES_DB=game_controller
    - POSTGRES_PASSWORD=pg_pass
    - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
    - game_controller_otus_pg_data:/var/lib/postgresql/data

  spaceship_webapi:
    image: spaceship-webapi
    container_name: spaceship_webapi_otus
    depends_on:
    - game_controller_api
    build: SpaceShip
    ports:
    - 5051:5216
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://+:5216
    - RABBITMQ_HOST=rabbitmq
    - RABBITMQ_USER=space-ship
    - RABBITMQ_PASSWORD=Ss1234
    - RABBITMQ_TROUBLES_QUEUE=q_troubles
    - RABBITMQ_STEP_QUEUE=q_new_day_ship

  rabbitmq:
    container_name: rabbitmq_otus
    build: RabbitMQ
    hostname: rabbitmq-otus
    ports:
    - 15672:15672
    - 5672:5672
    volumes:
    - rabbitmq_otus_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq_otus_data:
  game_controller_otus_pg_data:
