services:
  rabbitmq:
    container_name: rabbitmq_otus
    build: .
    hostname: rabbitmq-otus
    ports:
    - 15672:15672
    - 5672:5672
    volumes:
    - rabbitmq_otus_data:/var/lib/rabbitmq
    networks:
    - otus-space

volumes:
  rabbitmq_otus_data:

networks:
  otus-space:
    name: otus-space
