name: SpaceShip CI

on:
  push:
    branches: [ main ]
    paths:
    - SpaceShip/**
  pull_request:
    branches: [ main ]
    paths:
    - SpaceShip/**
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore SpaceShip/SpaceShip.sln

    - name: Build
      run: dotnet build SpaceShip/SpaceShip.sln --no-restore

    - name: Test
      run: dotnet test SpaceShip/SpaceShip.sln --no-build --verbosity normal
